plugin: aws_ec2
regions:
  - eu-west-1
filters:
  # This ensures Ansible only talks to the specific instance you built in Terraform. Matches the tag name in main.tf
  tag:Name: web-server 
hostnames:
  - public-ip-address
compose:
  # This tells Ansible to use the 'ubuntu' user for these AWS instances
  ansible_user: "ubuntu"